sudo: required
services:
  - docker

before_install: 
  - docker build -t anshulrana13/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anshulrana13/docker-react npm run test -- --coverage