resources:
- name: docker-react
  type: git
  source: 
    uri: https://github.com/AnshulRana13/docker-react.git
    branch: master
- name: react-app-image
  type: registry-image
  source:
    username: ((registry-username))
    password: ((registry-password))
    repository: ((image-repo-name))/react-app-image
jobs:
  - name: build-and-publish
    public: true
    plan:
      - get: docker-react
      - task: build-task-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          input:
          - name: docker-react
          output:
          - name: image
          params:
             DOCKERFILE: docker-react/Buildfiles
          run:
            path: build
      - put: react-app-image
        params:
          image: image/image.tar