resources:
- name: docker-react
  type: git
  source: 
    uri: https://github.com/AnshulRana13/docker-react.git
    branch: master
- name: my-image
  type: registry-image
  icon: docker
  source:
    repository: ((image-repo-name))/my-image
    username: ((registry-username))
    password: ((registry-password))
  
jobs:
  - name: build-and-push
    public: true
    plan:
      - get: docker-react
      - task: build-task-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          input:
          - name: docker-react
          output:
          - name: image
          params:
              CONTEXT: docker-react/Dockerfiles
          run:
            path: build
      - put: my-image
        params:
          image: image/image.tar